version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ticket_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: ticket_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - EMAIL=${EMAIL}
      - PASS=${PASS}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - DEBUG=${DEBUG}
      - OLLAMA_HOST=${OLLAMA_HOST}
    depends_on:
      - db

volumes:
  mysql_data:
