# Generated by Django 6.0.3 on 2026-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "email",
                    models.EmailField(max_length=30, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
