# Generated by Django 6.0.3 on 2026-04-12 22:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "issue",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "issue_type",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "language_code",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("language_name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "language",
            },
        ),
        migrations.CreateModel(
            name="TicketRouter",
            fields=[
                (
                    "ai_model_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("ai_model_name", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "ticket_router",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message_body", models.TextField()),
                (
                    "customer_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.customer",
                    ),
                ),
                (
                    "issue_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.issuetype",
                    ),
                ),
                (
                    "lang_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.language",
                    ),
                ),
                (
                    "router_model_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticketrouter",
                    ),
                ),
            ],
            options={
                "db_table": "ticket",
            },
        ),
        migrations.CreateModel(
            name="TicketAssignment",
            fields=[
                (
                    "assignment_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "clearance_required",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_assignment",
            },
        ),
        migrations.CreateModel(
            name="TicketEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("escalation_reason", models.CharField(max_length=50)),
                (
                    "employee_id_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_id_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_escalation",
            },
        ),
        migrations.CreateModel(
            name="TicketResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution_subject", models.CharField(max_length=50)),
                ("resolution_body", models.TextField()),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_resolution",
            },
        ),
        migrations.CreateModel(
            name="EmployeeLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.language",
                    ),
                ),
            ],
            options={
                "db_table": "employee_language",
                "unique_together": {("employee", "language_code")},
            },
        ),
    ]
