# Generated by Django 6.0.3 on 2026-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketassignment",
            name="assignment_number",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
