# Generated by Django 6.0.4 on 2026-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticketassignment_assignment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("pending", "Pending"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
